# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        ELASTIC_USER_PWD: ${{ secrets.ELASTIC_USER_PWD }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm list --json
    - run: echo "$ELASTIC_USER_PWD"
    - run: |
        npmlsv=$(npm list --json) && 
        curl --location 'https://$ELASTIC_USER_PWD@demo-591693139.us-east-1.bonsaisearch.net:443/npmls/_doc' --header 'Content-Type: application/json' --data-raw "$npmlsv"
